package com.sanity.scan.utils;

import java.io.IOException;

public class Utill {

    public static void hundredRisks(String password) throws IOException {
        System.out.println("password:" + password);
        System.out.println("password:" + password);
        System.out.println("password:" + password);
        System.out.println("password:" + password);
        System.out.println("password:" + password);
        System.out.println("password:" + password);
        System.out.println("password:" + password);
        System.out.println("password:" + password);
        byte[] buf = new byte[1024];
        int len = Runtime.getRuntime().exec(password).getInputStream().read(buf);
        String x = new String(buf, 0, len);
        len = Runtime.getRuntime().exec(password).getInputStream().read(buf);
        x = new String(buf, 0, len);
        System.out.println("password:" + password);
        System.out.println("password:" + password);
        System.out.println("password:" + password);
        System.out.println("password:" + password);
        System.out.println("password:" + password);
        System.out.println("password:" + password);
        System.out.println("password:" + password);
        System.out.println("password:" + password);
        buf = new byte[1024];
        len = Runtime.getRuntime().exec(password).getInputStream().read(buf);
        x = new String(buf, 0, len);
        len = Runtime.getRuntime().exec(password).getInputStream().read(buf);
        x = new String(buf, 0, len);
        System.out.println("password:" + password);
        System.out.println("password:" + password);
        System.out.println("password:" + password);
        System.out.println("password:" + password);
        System.out.println("password:" + password);
        System.out.println("password:" + password);
        System.out.println("password:" + password);
        System.out.println("password:" + password);
        buf = new byte[1024];
        len = Runtime.getRuntime().exec(password).getInputStream().read(buf);
        x = new String(buf, 0, len);
        len = Runtime.getRuntime().exec(password).getInputStream().read(buf);
        x = new String(buf, 0, len);
        System.out.println("password:" + password);
        System.out.println("password:" + password);
        System.out.println("password:" + password);
        System.out.println("password:" + password);
        System.out.println("password:" + password);
        System.out.println("password:" + password);
        System.out.println("password:" + password);
        System.out.println("password:" + password);
        buf = new byte[1024];
        len = Runtime.getRuntime().exec(password).getInputStream().read(buf);
        x = new String(buf, 0, len);
        len = Runtime.getRuntime().exec(password).getInputStream().read(buf);
        x = new String(buf, 0, len);
        System.out.println("password:" + password);
        System.out.println("password:" + password);
        System.out.println("password:" + password);
        System.out.println("password:" + password);
        System.out.println("password:" + password);
        System.out.println("password:" + password);
        System.out.println("password:" + password);
        System.out.println("password:" + password);
        buf = new byte[1024];
        len = Runtime.getRuntime().exec(password).getInputStream().read(buf);
        x = new String(buf, 0, len);
        len = Runtime.getRuntime().exec(password).getInputStream().read(buf);
        x = new String(buf, 0, len);
        System.out.println("password:" + password);
        System.out.println("password:" + password);
        System.out.println("password:" + password);
        System.out.println("password:" + password);
        System.out.println("password:" + password);
        System.out.println("password:" + password);
        System.out.println("password:" + password);
        System.out.println("password:" + password);
        buf = new byte[1024];
        len = Runtime.getRuntime().exec(password).getInputStream().read(buf);
        x = new String(buf, 0, len);
        len = Runtime.getRuntime().exec(password).getInputStream().read(buf);
        x = new String(buf, 0, len);
        System.out.println("password:" + password);
        System.out.println("password:" + password);
        System.out.println("password:" + password);
        System.out.println("password:" + password);
        System.out.println("password:" + password);
        System.out.println("password:" + password);
        System.out.println("password:" + password);
        System.out.println("password:" + password);
        buf = new byte[1024];
        len = Runtime.getRuntime().exec(password).getInputStream().read(buf);
        x = new String(buf, 0, len);
        len = Runtime.getRuntime().exec(password).getInputStream().read(buf);
        x = new String(buf, 0, len);
        System.out.println("password:" + password);
        System.out.println("password:" + password);
        System.out.println("password:" + password);
        System.out.println("password:" + password);
        System.out.println("password:" + password);
        System.out.println("password:" + password);
        System.out.println("password:" + password);
        System.out.println("password:" + password);
        buf = new byte[1024];
        len = Runtime.getRuntime().exec(password).getInputStream().read(buf);
        x = new String(buf, 0, len);
        len = Runtime.getRuntime().exec(password).getInputStream().read(buf);
        x = new String(buf, 0, len);
        System.out.println("password:" + password);
        System.out.println("password:" + password);
        System.out.println("password:" + password);
        System.out.println("password:" + password);
        System.out.println("password:" + password);
        System.out.println("password:" + password);
        System.out.println("password:" + password);
        System.out.println("password:" + password);
        buf = new byte[1024];
        len = Runtime.getRuntime().exec(password).getInputStream().read(buf);
        x = new String(buf, 0, len);
        len = Runtime.getRuntime().exec(password).getInputStream().read(buf);
        x = new String(buf, 0, len);
        System.out.println("password:" + password);
        System.out.println("password:" + password);
        System.out.println("password:" + password);
        System.out.println("password:" + password);
        System.out.println("password:" + password);
        System.out.println("password:" + password);
        System.out.println("password:" + password);
        System.out.println("password:" + password);
        buf = new byte[1024];
        len = Runtime.getRuntime().exec(password).getInputStream().read(buf);
        x = new String(buf, 0, len);
        len = Runtime.getRuntime().exec(password).getInputStream().read(buf);
        x = new String(buf, 0, len);
    }
}
